### ISSUE TITLE
FingerprintManager.CryptoObject is deprecated

### ISSUE THREAD

**Issue by cgomezmendez** [SelfLender/react-native-biometrics#11]
https://github.com/SelfLender/react-native-biometrics/blob/1e53f8f6f2d156e2ac29f0de4089c1408a43b445/android/src/main/java/com/rnbiometrics/ReactNativeBiometricsCallback.java#L11

> 
> This class was deprecated in API level 28.
> See BiometricPrompt.CryptoObject
https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.CryptoObject

**Comment by NappyPirate** [comment]
relates to issue https://github.com/SelfLender/react-native-biometrics/issues/15
