### ISSUE TITLE
SDK Target expiring soon

### ISSUE THREAD

**Issue by cgomezmendez** [SelfLender/react-native-biometrics#12]
Google Play will soon require that apps target API level 26 or higher. This will be required for new apps in August 2018, and for updates to existing apps in November 2018

In the second half of 2018, Google Play will require that new apps and app updates target API level 26 or higher. This will be required for new apps in August 2018, and for updates to existing apps in November 2018.  Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion).  This lint check starts warning you some months before these changes go into effect if your targetSdkVersion is 25 or lower. This is intended to give you a heads up to update your app, since depending on your current targetSdkVersion the work can be nontrivial.  To update your targetSdkVersion, follow the steps from "Meeting Google Play requirements for target API level", https://developer.android.com/distribute/best-practices/develop/target-sdk.html  Issue id: ExpiringTargetSdkVersion  More info: https://support.google.com/googleplay/android-developer/answer/113469#targetsdk https://developer.android.com/distribute/best-practices/develop/target-sdk.html

**Comment by NappyPirate** [comment]
The default android SDK has been updated to 28 in version [1.2.0](https://github.com/SelfLender/react-native-biometrics/compare/1.1.3...1.2.0)
