### ISSUE TITLE
Android-Face Recognition not working

### ISSUE THREAD

**Issue by RNTop** [SelfLender/react-native-biometrics#125]
Android-Face Recognition not working.

**Comment by harshithagb** [comment]
Same here. Face authentication not working.

**Comment by JZorina** [comment]
same here

**Comment by NetPumi2** [comment]
Android face is working on Google Pixel 4 but it is not working on Samsung A22 and it should work

**Comment by jayfunk** [comment]
There is a set of Samsung face recognition that was blacklisted by Google. I believe some of those devices were blacklisted. Which means they are not supported by https://developer.android.com/jetpack/androidx/releases/biometric biometrics purposes.
