### ISSUE TITLE
TypeError: Null is not an object (evaluating bridge.isSensorAvailable)

### ISSUE THREAD

**Issue by developerRio** [SelfLender/react-native-biometrics#126]
Not working in Android 10

console Logs: [Unhandled promise rejection: TypeError: null is not an object (evaluating 'bridge.isSensorAvailable')]

**Comment by shemilhashan** [comment]
same for ios. any updates?

**Comment by keselme90** [comment]
@shemilhashan @developerRio Do you remember what was the problem?

**Comment by mitchiemt11** [comment]
Changing the directory to ios folder and run `pod install` worked for me.
