### ISSUE TITLE
Need Reference verify for backend

### ISSUE THREAD

**Issue by edoofx** [SelfLender/react-native-biometrics#130]
can someone gimme a reference nodejs for verify pair key ?

because at doc using .py

**Comment by kristerkari** [comment]
Here:
https://github.com/SelfLender/react-native-biometrics/issues/32#issuecomment-502183513

**Comment by edoofx** [comment]
> Here:
> [#32 (comment)](https://github.com/SelfLender/react-native-biometrics/issues/32#issuecomment-502183513)

thanks ..

i appreciate it
