### ISSUE TITLE
Allow PIN, Pattern for Android device in case of fallback.

### ISSUE THREAD

**Issue by reactnative103** [SelfLender/react-native-biometrics#131]
Hi,

Can you please allow PIN, Pattern for Android device in case of fallback.

setDeviceCredentialAllowed is required to allow fallback systems (PIN, Pattern, etc) to be used by user's choice. Is there a way we can get this to be configureable?

Thanks & Regards,

**Comment by kg-currenxie** [comment]
I would love this as well.

I have tried adding `.setDeviceCredentialAllowed(true)` to the java `new PromptInfo.Builder()`, but it seems that the fingerprint popup doesn't even show.

I've also tried `.setUserAuthenticationRequired(false)` in createKeys, but it also results in not working. 

Anyone have any ideas?

**Comment by NKGS** [comment]
Yes it will be great to have this feature.. If someone has any suggestion for library that supports pin/pattern do share them.

**Comment by jayfunk** [comment]
This is to be implemented in the #183 PR. Once that is merged you will have device auth as a fallback.
