### ISSUE TITLE
simplePrompt or createSignature after start app long time no showing dialog biometry

### ISSUE THREAD

**Issue by maystrenkoYurii** [SelfLender/react-native-biometrics#132]
simplePrompt or createSignature after start app long time no showing dialog biometry after click button (delay 3-8 sec interval) for call dialog android only

createSignature in issue blocked ui thread but simplePrompt not blocked(android)
![Screenrecorder-2020-07-27-11-12-20-792](https://user-images.githubusercontent.com/23016311/88519203-661a6180-cffa-11ea-81f5-4abf6765d44c.gif)

**Comment by shriomsystematix** [comment]
hello, @maystrenkoYurii are you got any solution? I am also facing the same problem in 2gb ram phone.
