### ISSUE TITLE
Not clear how to reveal user on backend.

### ISSUE THREAD

**Issue by skrivitsky** [SelfLender/react-native-biometrics#135]
I use JWT as middleware for my endpoints. When user login in casual way, I prompt him to enable biometric auth.
Then he agrees and I generate public key and send it to the backend., 
User logout and want to auth again via biometrics.
I createSignature and send it to the backend. How backend will verify signature if it doesnt know which user's public key search for?
Help, please.
Thank you in advance)

**Comment by kristerkari** [comment]
@skrivitsky you need to assign the public key to a user, otherwise you can not know which user to login after doing the verification. Keep in mind that the user can have multiple devices, so it should be something like user->device_id->public_key

**Comment by skrivitsky** [comment]
@kristerkari I send public key on sign up, it worked like you described. Then I call `createSignature` with `payload=deviceId`, searching user with this device id and if signature verified I return token.
Is my logic correct?
Thank you)
