### ISSUE TITLE
not able to create key with face recognition in android10 

### ISSUE THREAD

**Issue by JZorina** [SelfLender/react-native-biometrics#142]
once the face recognition is configue on the device without the fungerprint - i get this error :

  **Error generating public private keys
    at Object.promiseMethodWrapper [as createKeys] -....\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:103)
    at Object.createKeys (......\node_modules\react-native-biometrics\build\cjs\index.js:33)**

what can i do to fix this?

**Comment by ChhenglinHor** [comment]
Guys, any update on this? I had the same issue.

**Comment by jayfunk** [comment]
I would suggest using the latest version as we updated to a newer version of Android's biometric libraries.
