### ISSUE TITLE
Slow biometric works incorrectly on Android

### ISSUE THREAD

**Issue by VashaMasha** [SelfLender/react-native-biometrics#145]
ReactNativeBiometrics.simplePrompt works extremely slowly on Android. 
I am testing biometric authentication on Xiaomi Redmi Note 8 Pro.
When user opens the app he is asked to sign in with biometric. User has to wait several seconds until the modal is shown to use it. And after that wait another 20-30 seconds for success enter.  
Sometimes the app even freezes and does not open biometric modal at all.

This process works flawlessly for iOS and other android devices. The main problem for me is in Xiaomi Redmi Note 8 Pro.

"react-native": "^0.63.2",
"react-native-biometrics": "^2.1.4", 
"react-native-keychain": "^6.2.0",

**Comment by martinhellwig** [comment]
Hi @VashaMasha. The problem with long loading times may come from react-native-keychain. We also got long loading times only on Android 10+ devices. On Android 9 and prior as well as on iOS the loading times were good.
Check this issue: https://github.com/oblador/react-native-keychain/issues/337
