### ISSUE TITLE
Ghost keyboard after FaceID

### ISSUE THREAD

**Issue by Hirurgo** [SelfLender/react-native-biometrics#153]
I faced with interesting keyboard issue described here https://www.reddit.com/r/iphone/comments/f5zb6t/ghost_keyboard_bug_on_faceid_devices_ios_12current/

After faceId, I put a focus on some input and the invisible keyboard will open and I can write some text. To open the normal keyboard I need to put focus again.

Just leave my solution here:

```
  useEffect(
    () => {
      // NOTE show and immediately hide keyboard
      // fix of ghost keyboard https://www.reddit.com/r/iphone/comments/f5zb6t/ghost_keyboard_bug_on_faceid_devices_ios_12current
      if (Platform.OS === 'ios') {
        typeof inputRef?.current?.focus === 'function' && inputRef?.current?.focus();
        setTimeout(
          () => Keyboard.dismiss(),
          0
        );
      }
    },
    []
  );
```

**Comment by jayfunk** [comment]
Thank you for the suggestion. Closing.
