### ISSUE TITLE
CreateSignature doesn't open prompt

### ISSUE THREAD

**Issue by sunriseshoapeng** [SelfLender/react-native-biometrics#154]
Hello, simple prompt opens but create signature doesnt open on Android Simulator. Using Google Pixel 4 with API 30, Release name R.

**Comment by sunriseshoapeng** [comment]
Error: Error generating signature: Supplied key (null) is not a RSAPrivateKey instance
promiseMethodWrapper@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3126:45
triggerButtonTest$
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25832:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26005:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25832:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25905:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25935:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27923:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28087:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27946:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25934:33
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25939:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25956:69
onPress
_performTransitionSideEffects@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:56425:22
_receiveSignal@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:56367:45
onResponderRelease@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:56276:34
invokeGuardedCallbackImpl@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10034:21
invokeGuardedCallback@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10128:42
invokeGuardedCallbackAndCatchFirstError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10132:36
executeDispatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10204:48
executeDispatchesInOrder@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10224:26
executeDispatchesAndRelease@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11299:35
forEach@[native code]
forEachAccumulated@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10366:22
runEventsInBatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11323:27
runExtractedPluginEventsInBatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11402:25
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11378:42
batchedUpdates$1@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:22027:20
batchedUpdates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11285:36
_receiveRootNodeIDEvent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11377:23
receiveTouches@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:11430:34
__callFunction@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3657:36
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3389:31
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3611:15
callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3388:21
callFunctionReturnFlushedQueue@[native code]

**Comment by shagufta101** [comment]
@sunriseshoapeng Please try running in real device. It should work!!

**Comment by dsho1288** [comment]
I have the same error and I am running in a real device
