### ISSUE TITLE
Image(Readme.md) can't see it well in darkmode.

### ISSUE THREAD

**Issue by karriz-dev** [SelfLender/react-native-biometrics#158]
In readme.md darkmode, image can't see it well.

It would be even better to change the background 'white' (or something..)

![스크린샷 2021-03-31 10 32 31](https://user-images.githubusercontent.com/10491607/113077759-b80c2a80-920c-11eb-83db-2068cd07233e.png)

**Comment by jayfunk** [comment]
Fixed.
