### ISSUE TITLE
Dont allow case how we can hide Button of faceId/TouchId

### ISSUE THREAD

**Issue by ahtisham09** [SelfLender/react-native-biometrics#160]
![D2C1226B-28EC-474A-8BA0-22C743C0CCED](https://user-images.githubusercontent.com/59255791/113392349-6d2a1880-93ae-11eb-8a31-599ae0aa7fe3.jpeg)

if use dont allow how to hide faceId button which open simplePrompte

**Comment by jayfunk** [comment]
You should be able to call `isSensorAvailable`  before hand to determine if the user allowed the application to use FaceID.
