### ISSUE TITLE
Unhandled promise rejection: TypeError: null is not an object (evaluating 'bridge.isSensorAvailable')

### ISSUE THREAD

**Issue by DougHigashi** [SelfLender/react-native-biometrics#170]
```import React from 'react';
import { TouchableOpacity, View, StyleSheet, Text } from 'react-native';
import { Ionicons } from "@expo/vector-icons";
import ReactNativeBiometrics from 'react-native-biometrics';
 
export default function Login() {

  const auth = async () => {
    const { biometryType } = await ReactNativeBiometrics.isSensorAvailable()
      .then(() => {
        if (biometryType === ReactNativeBiometrics.Biometrics) {
          console.log('Biometrics adquired');
        }
      }).catch(() => {
        console.log('Biometrics failed');
      })
  }

  return (
    <View style={styles.container}>
        <Text style={styles.text}>Authenticate please</Text>

        <TouchableOpacity style={styles.logo} onPress={auth}>
          <Ionicons name="finger-print" color="white" size={128}/>
        </TouchableOpacity>
    </View>
  );
}
```
project react native version: "0.63.2"
react-native-biometrics version: "2.1.4"

Couldn't find anything about this error...

**Comment by DougHigashi** [comment]
So just figured out that this library doesn't work with expo.

**Comment by JoseVov** [comment]
Hi @DougHigashi 

Does this mean that after you run `expo eject` this module started to work?

**Comment by JoseVov** [comment]
I downgrade the version to 2.1.1 and that fix it

**Comment by DougHigashi** [comment]
> Hi @DougHigashi
>Does this mean that after you run expo eject this module started to work?
No, I started all over with a pure react native project

**Comment by mitchiemt11** [comment]
I was facing the same issue but after I realized that I forgot to run I run `npx pod install ` in the terminal, it worked!

**Comment by JoseVov** [comment]
It worked for me on android but now I'm trying to test on an iPhone and is not working 😢 . So I guess the only way is to remove completely `expo` as @DougHigashi mentioned
