### ISSUE TITLE
Key generation error received upon updating Xcode 13.0 (iOS 15)

### ISSUE THREAD

**Issue by Angulo66** [SelfLender/react-native-biometrics#171]
I had no issues with using `createKeys()` function on android devices and earlier iOS devices/simulators, but i just recently updated Xcode and it's simulators to iOS 15 and i'm getting this error in my console, i'm not doing anything fancy using server-side and just implementing just on client-side due to having other layers of security in app:

<img width="657" alt="Screen Shot 2021-10-11 at 22 40 17" src="https://user-images.githubusercontent.com/31868336/136892511-3a566cca-4551-4351-937b-6871f0d6bb8d.png">

<img width="512" alt="Screen Shot 2021-10-11 at 22 47 01" src="https://user-images.githubusercontent.com/31868336/136893162-eb9184db-a48f-4fe4-92cd-234541bee7be.png">

```
"react-native": "0.64.0"
"react-native-biometrics": "^2.1.4"
```

**Comment by linhpa** [comment]
looks like the error only occures on simulator. it works well on real device for me.

**Comment by kg-currenxie** [comment]
Same issue. So this is an issue with Apple? 🤔

**Comment by kg-currenxie** [comment]
To test in a Simulator, create a device with ios 14.5 as a workaround. But it works on a real device with 15.

![Screenshot 2022-05-05 at 17 38 34](https://user-images.githubusercontent.com/48229166/166898437-147f7443-eca5-4d78-a8dd-0bd94036c895.png)

**Comment by jayfunk** [comment]
Did some digging on this issue. So far the only thing that seems to point to this being a bug on Apple's side. I found in this thread there is a bug being tracked regarding this very issue. 

https://developer.apple.com/forums/thread/685773

**Comment by jayfunk** [comment]
Since this issue appears to be outside of this libraries control I am going to close this issue.

**Comment by iamisathya** [comment]
> To test in a Simulator, create a device with ios 14.5 as a workaround. But it works on a real device with 15.
> 
> ![Screenshot 2022-05-05 at 17 38 34](https://user-images.githubusercontent.com/48229166/166898437-147f7443-eca5-4d78-a8dd-0bd94036c895.png)

Thanks, it's working on iOS 14.5 simulator.
