### ISSUE TITLE
How to authenticate the user

### ISSUE THREAD

**Issue by MarioUnlam** [SelfLender/react-native-biometrics#175]
I don't understand how this plugin works. Once the user does the biometrics check and I send the signature to the server, what do I do with it? Let's suppose I have AWS Cognito as the authenticator. To let the user sign in with biometrics I need his username and password. To get this info during verification, I would need to either use the credentials as the signature payload (which requires storing the credentials inside the mobile device), or store the credentials in my server database to retrieve after the verification is successful. None of those methods are safe, credentials should not be saved anywhere. Maybe I'm missing something?

**Comment by JorgeChSoefe** [comment]
Hi, you only need to call the ReactNativeBiometrics.createKeys() method, in the promise return the public key
