### ISSUE TITLE
Prompt not showing on Android

### ISSUE THREAD

**Issue by barbalata** [SelfLender/react-native-biometrics#177]
Hello,

When I'm calling the method `ReactNativeBiometrics.createSignature`, for the bellow device it's not showing the prompt, it only activates the fingerprint sensor (the device has the fingerprint inside of the device). Also, the functions defined for `then`, `catch`, or `finally` are not called. 

I've tried on multiple devices, with different Android versions (including another OnePlus 6T, with Android version 11), but I cannot replicate the behavior.

- Package version: ^2.1.4
- React version: 16.13.1
- React Native version: ~0.63.4
- Device model: OnePlus 6T
- OS Version: OxigenOS
- Android Version: 10.3.11

**Comment by jayfunk** [comment]
Are you getting the prompt when creating the keys?

**Comment by jayfunk** [comment]
Closing since no response has been received to attempt to address this issue.
