### ISSUE TITLE
Maintenance 

### ISSUE THREAD

**Issue by rohit4812** [SelfLender/react-native-biometrics#182]
See that the last update happened way back in Feb 2020? We were planning to get the biometrics feature gets introduced into our React Native App. Do we have any plans for maintaining this library in terms of if there is a new update coming from IOS or Android World?

**Comment by jayfunk** [comment]
Yes! The Self team has been focused on other efforts, but are committed to continued maintenance of this project. In the next coming weeks you should start to see more activity on this repo.
