### ISSUE TITLE
Face ID not showing 

### ISSUE THREAD

**Issue by dhairyasenjaliya** [SelfLender/react-native-biometrics#186]
for iOS, after asking for faceID permission it shows the face id sensor for 1 time then after if I try to use the method simple prompt  not showing the face scanner and in error, it gives null as a response 

also face id not inconsistency some time it shows some time doesn't 

anybody has any solution ?

**Comment by jayfunk** [comment]
Can you give some details on the device you are using for testing?

**Comment by dhairyasenjaliya** [comment]
I'm using iPhone X ios 15

**Comment by jayfunk** [comment]
Could you give a snippet of how you have implemented the library? Also have you tried this on another device or on an android device?

Regards,
Tyler Cook

**Comment by jayfunk** [comment]
Have you already configured `NSFaceIDUsageDescription` permission?

**Comment by dhairyasenjaliya** [comment]
<img width="820" alt="Screenshot 2022-05-25 at 10 41 56 AM" src="https://user-images.githubusercontent.com/47522946/170184594-e2a9f4a3-76c8-4cc3-809a-08990046dcf4.png">
Yup

**Comment by jayfunk** [comment]
Would you be able to try out the 3.0.1 version of the package? Can you provide any stack traces?

**Comment by dhairyasenjaliya** [comment]
working now thanx

**Comment by alienbalcorp** [comment]
> <img alt="Screenshot 2022-05-25 at 10 41 56 AM" width="820" src="https://user-images.githubusercontent.com/47522946/170184594-e2a9f4a3-76c8-4cc3-809a-08990046dcf4.png">
> 
> Yup

It helped me, thanks!

**Comment by abhishek-capsitech** [comment]
> Author

It was helpful, Thanks!
