### ISSUE TITLE
Veracode Vulnerability issue

### ISSUE THREAD

**Issue by rkaartikeyan** [SelfLender/react-native-biometrics#189]
First of all thanks for this great RN library.

We are observing a vulnerability with Veracode. Kindly find the below details. Just want to share this to ensure the security of this great library.

```
Description: This call to LAContext.evaluatePolicy:localizedReason:reply:(), while sufficient in most cases, is dangerous for higher risk applications such as banking.

Remediation: Best practice for such applications is to use access control services within the iOS keychain. This protects against tools designed to bypass LocalAuthentication.

```

![image](https://user-images.githubusercontent.com/3778591/171867108-e75f4cc1-8096-4202-9d42-19081de5c442.png)

**Comment by gclark-eightfold** [comment]
@rkaartikeyan This is only be an issue when using [simplePrompt](https://github.com/SelfLender/react-native-biometrics#simplepromptoptions). If you're only using [createSignature](https://github.com/SelfLender/react-native-biometrics#createsignatureoptions) and validating the digital signature with a server you registered the public key with, then you should have no problems security-wise.

If tools like Veracode simply scan all the include source files for certain references, you'll always see this pop up. If you want to remove this entirely, you can remove the `simplePrompt` function from your source files entirely (and remove any references to it) with something like [patch-package](https://www.npmjs.com/package/patch-package).
