### ISSUE TITLE
[Question] How can i get public key without having to authenticate by fingerprint?

### ISSUE THREAD

**Issue by kamvoick** [SelfLender/react-native-biometrics#19]
Ok, so i'm trying to figured out how to get public key and store it inside keystore without having to use biometric authentication. I just want to get it just when user's device is capable of biometrical authentication (has a fingerprint scanner or so) but without prompt for fingerprint. It's a case when i'd like to sent public key (at the begging - let's say at registration process) onto my server, and left choice for using biometric auth for user whenever he needs it (or have set it in settings menu). 
Thanks 

Btw. very useful lib, thank you!

**Comment by jinshin1013** [comment]
I can see the benefit of being able to generate public/private keys without having to go through biometric authentications. Some app requires a flow like:

1. User toggles to enable FaceID/TouchID
2. User enters their app passcode to authenticate
3. Public/Private keys are generated to send and use with the api. 

In this flow, as the user already authenticates themselves with the app passcode, we do not want them to have to authenticate twice (both biometric and passcode auth). 

Do you see any potential security problem with generating public/private keys without proper biometric authentication?

**Comment by howitworks18** [comment]
this is a feature thats being requested in an app im currently working on as well.

Our flow: 
1. Asks if you want to use biometrics via Alert.prompt
2. Create a pin thats stored in the app

Later when using the pin, the app recognizes that the user wants to use biometrics in place of the pin but the OS prompts for permission. 

The ability to generate public/private keys without going through the biometric authentication does seem like it might have some security issues tho.

**Comment by NappyPirate** [comment]
I just released [1.5.0](https://github.com/SelfLender/react-native-biometrics/releases/tag/1.5.0) which adds the ability to prevent the biometric prompt from displaying by omitting the `promptMessage` parameter

**Comment by jinshin1013** [comment]
Thanks @NappyPirate, really appreciate for this!
