### ISSUE TITLE
ReactNativeBiometrics.isSensorAvailable got 2 arguments, expected 3

### ISSUE THREAD

**Issue by agussproutasia** [SelfLender/react-native-biometrics#192]
Hi Guys, i have some issue when i build with ms appcenter ci/cd the apps crash when runing biometric function, but when i build with my local laptop everything is normal, can you help me guys?

<img width="1123" alt="Screen Shot 2022-06-20 at 10 58 50" src="https://user-images.githubusercontent.com/107821568/174523131-6820784d-46d9-4cca-805b-bf119b2bbb67.png">

here the function:
`export const BiometricAvailability = async () => {
  const {available, biometryType, error} =
    await ReactNativeBiometrics.isSensorAvailable();
  if (available && biometryType === ReactNativeBiometrics.TouchID) {
    return true;
  } else if (available && biometryType === ReactNativeBiometrics.FaceID) {
    return true;
  } else if (available && biometryType === ReactNativeBiometrics.Biometrics) {
    return true;
  } else {
    console.log('Biometrics not supported', error);
    return false;
  }
};`

here when i call the function:
`const isBiometricAvailable = await BiometricAvailability();`

**Comment by jayfunk** [comment]
Refer to this thread for details on how to resolve. https://github.com/SelfLender/react-native-biometrics/issues/191#issue-1271654197
