### ISSUE TITLE
How verify signature in backend NodeJs

### ISSUE THREAD

**Issue by Joshig99** [SelfLender/react-native-biometrics#197]
Hi i checked this ticket https://github.com/SelfLender/react-native-biometrics/issues/32#issuecomment-502183513, i used this code its returning always `false` 

       
      const NodeRSA = require('node-rsa');

       function main(){
       const publicKey = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzZZtAhOx70ej7/ymjPsOjz+2sL3vAwiAvit3p0uelwLr1Djz9Yrq7owH4lefIvI8mwdLYYqbCvkryIlGjSVb5DIux8TZ09ZaUjB+o7et+ZylVRdvQHImGtH8xjXhkbZAPuM/p/6qz1XInD8GkXNP8n9Nh76uY6NnJBN/uvMKJWy9Q48mXd148ZBBzm3IV50NF6hb1buubNgM39MQ4tpEYJFwPSfcsa9evz03tqmXRGIvChDYp5uSNTCxV/TVDqdQOxdsfjNp7o11V7vJhPzDjveekHtiZm8pMYYZ9JqWxI6H3fPXtG9wkK+Oa51xnMXbGYVseo2k8BbM+ek5yfXk/wIDAQAB'
       const payload = 'example auth key'
       const signature = 'UI8RRMvGB171vy9RAYSKUhy0v4Xm9+jdCs03aeqM+gAi5N2lihVXIs2fLY5Qsw2AY67z3/Z6GikVk8sXD0gua4Gr2Hi3+FzpWl+U7T3uvnskrGaEPsiFsURAxSKD2hmWXSUcSxGKSoChkP9KC3Q0HcJlQw9+/24fzHiByI1Wj8gHVAH9HM6t2fiz8vFSr2ddiKHdkM5lu7Q59Xb9JelxZrMAs2OlMwhVv190PYAWXjGmDFzDP2DfmEz5etG5XRB54FijvwOSzB4zxWEJdI3+Fp+Rf0j3fPgq665U2drjRCBj6fLtDi9wUTHSMpXmMlbLMLrF2cqhqH6VO71BFS2U5w=='

       const publicKeyBuffer = Buffer.from(publicKey, 'base64')
       const key = new NodeRSA()
       const signer = key.importKey(publicKeyBuffer, 'public-der')
       const signatureVerified = signer.verify(Buffer.from(payload), signature, 'utf8', 'base64')

       console.log(signatureVerified)
       }
       main()

and this is my front-end code 
      
         const onRegister = async () => {
           const rnBiometrics = new ReactNativeBiometrics({
               allowDeviceCredentials: true,
              });
           rnBiometrics
           .isSensorAvailable(BiometryTypes.Biometrics)
          .then(resultObject => {
          const {available, biometryType} = resultObject;
         if (available && biometryType === BiometryTypes.TouchID) {
              console.log('TouchID is supported');
             } else if (available && biometryType === BiometryTypes.FaceID) {
              console.log('FaceID is supported');
            } else if (available && biometryType === BiometryTypes.Biometrics) {
          console.log('Biometrics is supported');
          rnBiometrics.biometricKeysExist().then(result => {
            let epochTimeSeconds = Math.round(
              new Date().getTime() / 1000,
            ).toString();
            let payload = epochTimeSeconds + 'example auth key';
            const biometrics = new ReactNativeBiometrics();
            const {keysExist} = result;
            if (keysExist) {
              console.log('Keys exist');
              biometrics
                .createSignature({
                  promptMessage: 'Sign in',
                  payload: payload,
                })
                .then(response => {
                  const {success, signature} = response;
                  console.log('resultObject', response);
                  if (success) {
                    console.log(signature);
                    // verifySignatureWithServer(signature, payload);
                  }
                });
            } else {
              console.log('Keys do not exist or were deleted');

              biometrics
                .createKeys()
                .then(async response => {
                  const {publicKey} = response;
                  console.log(publicKey, 'publicKey');
                  // sendPublicKeyToServer(publicKey)
                  await AsyncStorage.setItem('signature', publicKey);
                  biometrics
                    .createSignature({
                      promptMessage: 'Sign in',
                      payload: payload,
                    })
                    .then(response => {
                      const {success, signature} = response;
                      console.log('resultObject', response);
                      if (success) {
                        console.log(signature);
                        // verifySignatureWithServer(signature, payload);
                      }
                    });
                })
                .catch(error => {
                  console.log(error, 'error in creating keys');
                });

              // const biometrics = new ReactNativeBiometrics();
            }
          });
        } else {
          console.log('Biometrics not supported');
        }
      })
      .catch(err => {
        console.log('TouchID is not available: ', err);
      });
  };

**Comment by Joshig99** [comment]
its working, i given wrong payload

**Comment by vokoye** [comment]
What payload did you use eventually, still cannot get my head around this flow. How do you know the right public key to decode with?
