### ISSUE TITLE
Release 2.2.0 has breaking change!

### ISSUE THREAD

**Issue by sharifhh** [SelfLender/react-native-biometrics#200]
Please remove 2.2.0 and name it 3.0.0 because it is not backward compatible but it has a breaking change.

You changed the whole way we call the library in react-native, now we need to use the constructor so the old code is breaking.

I guess there is no way to remove 2.2.0 but you can release 2.1.4 as 2.2.1 and release 2.2.0 as 3.0.0.

Thanks,

**Comment by jayfunk** [comment]
This has been done. Thank you for the suggestion.
