### ISSUE TITLE
Create Keys Fails On iOS 

### ISSUE THREAD

**Issue by PNFalewis** [SelfLender/react-native-biometrics#201]
every time i try to call create keys on ios i get the following error

`[Error: Key generation error: Error Domain=NSOSStatusErrorDomain Code=-25293 "Key generation failed, error -25293" UserInfo={numberOfErrorsDeep=0, NSDescription=Key generation failed, error -25293}]`

anybody else encounter something similar?

**Comment by algarcia-vector** [comment]
I am having the same issue :(, someone knows how to fix it?

**Comment by siniarski** [comment]
From my testing this looks to be an issue specific to iOS 15 simulators. The issue happens in `react-native-biometrics/iOS/ReactNativeBiometrics.m` on line `69` when `SecKeyCreateRandomKey` is used to try and generate a key.
![Screen Shot 2022-07-14 at 4 46 19 pm](https://user-images.githubusercontent.com/31227087/178918913-ec8448e8-bf39-43b7-bb49-cb4b76470c3a.png)

However testing an iOS 15 device and iOS 14 simulator which worked as expected. Most likely an issue with iOS 15 simulators using the Secure Enclave.

**Comment by jeveloper** [comment]
I'd say bake in the logic to check for simulator and not use anything of this library. This is done on purpose as there is no iCloud service on simulator that carries iCloud Keychain.

**Comment by jayfunk** [comment]
This issue is known and outlined in the [troubleshooting section](https://github.com/SelfLender/react-native-biometrics#troubleshooting). This issue is believed to be an issue on the iOS Simulator side and one we are not going to address in this project.
