### ISSUE TITLE
Obtain private key for decrypt functionality

### ISSUE THREAD

**Issue by julian-trustgrid** [SelfLender/react-native-biometrics#203]
Hi guys,

I'm wondering how we can obtain a private key for decryption purposes? I'm about to use this library to be able to encrypt files/data using the public key and decrypt them using private keys.

Is this possible?

Thanks

**Comment by jayfunk** [comment]
This library does not expose the private key. You are able to sign content with the private key using `createSignature`. Which would be what you use when communicating with some backend service reading the biometric data.
