### ISSUE TITLE
How to know the device has biometrics function or not?

### ISSUE THREAD

**Issue by DonRyu** [SelfLender/react-native-biometrics#204]
Version 
"react-native": "0.68.2",
 "react-native-biometrics": "^2.2.0",
 buildToolsVersion = "30.0.0"
 minSdkVersion = 21
  compileSdkVersion = 31
  targetSdkVersion = 30

Code
```
 rnBiometrics.isSensorAvailable()
        .then((resultObject) => {
          const {available, biometryType} = resultObject
          if (Platform.OS === 'ios') {
            if (available && biometryType === BiometryTypes.FaceID) {
              setNoBioAuth(false)
            } else {
              setNoBioAuth(true)
            }
          } else {
            if (available && biometryType === BiometryTypes.Biometrics) {
              setNoBioAuth(false)
            } else {
              setNoBioAuth(true)
            }
          }
        })

```

What I want...
Want to know the device has biometrics function (fingerprint or face id)  or not 

The current app do...
Even my galaxy a32 has fingerprint function, if there is no fingerprint data at setting 
Above function regard biometrics is not available...

**Comment by cocoburger** [comment]
It's been quite some time. 

1. android studio open 
2. open the file react-native-biometrics > android > src > main > java> com > rnbiometrics > ReactNativeBiometrics
3. You can find code like   "case BiometricManager.BIOMETRIC_ERROR_NO_HARDWARE:"
4. the line check breakpoint
5. run build
6. done

**Comment by jayfunk** [comment]
Closing as @cocoburger answered the question.
