### ISSUE TITLE
The public key stored doesn't match with signature 

### ISSUE THREAD

**Issue by bbeckk** [SelfLender/react-native-biometrics#21]
I am trying to use this biometrics but after I've created and stored the public key, it never matches with the signature generated afterward with the same finger. How can I verify the fingerPrint?

Test Code:

```
  registerFingerPrint = () => {
    Biometrics.isSensorAvailable()
    .then((biometryType) => {
      if (biometryType === Biometrics.TouchID) {
        Biometrics.createKeys('Confirm fingerprint')
        .then((publicKey) => {
          console.log("create", publicKey)
          this.setState({
            create: publicKey
          })
        })
      } 
    })
  }

  fingerPrintCheck = () => {
    Biometrics.createSignature('Sign in', payload)
    .then((signature) => {
      if (this.state.create === signature){
        console.log("success");
      }else {
        console.log('failure'); //always returns failure here
      }
    })
  }

  render() {
    return (
      <View style={styles.container}>

        <TouchableHighlight onPress={()=> this.registerFingerPrint()}>
          <Text style={{ marginBottom: 10}}>
            Register
          </Text>
        </TouchableHighlight>

        <TouchableHighlight onPress={()=> this.fingerPrintCheck()}>
          <Text>
            Authenticate with Biometrics
          </Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

**Comment by kamvoick** [comment]
I think you misunderstood the conception about pairing device with signature. You have 2 keys - public and private, when creating your public key you're sending it onto the server and then you can verify your identity on the server by decoding signature (which is pushed when needed) with public key that you sent earlier. So to sum up, the signature is 

> a RSA PKCS#1v1.5 SHA 256 signature

generated with your private key. Ther're not equal. And btw you missed somewhere payload which is also important

**Comment by NappyPirate** [comment]
@kamvoick is correct, you must verify the generated signature using the public key and the payload that was used to create the signature.  Here is an example of how you would do that server side using python https://gist.github.com/lkdocs/6519372

**Comment by psemwal** [comment]
Hi ,
I am storing the public key in server and after that verify the signature .I am always getting
false result means its not validating.I using Java api to validate Signature.

Thanks,
Pankaj

**Comment by JawwDeeK** [comment]
Hi,

@psemwal this is how you have to do it in java:

```java
public boolean verifySignature(String signature, String payload, String pubKey) {
    boolean result = false;
    
    try {
      final KeyFactory keyFactory = KeyFactory.getInstance("RSA");
      X509EncodedKeySpec publicKeySpec = new X509EncodedKeySpec(Base64.getDecoder().decode(pubKey));
      PublicKey key = keyFactory.generatePublic(publicKeySpec);
      
      Signature sha_rsa = Signature.getInstance("SHA256withRSA");
      sha_rsa.initVerify(key);
      sha_rsa.update(payload.getBytes());
      
      result = sha_rsa.verify(Base64.getDecoder().decode(signature));
    } catch (Exception e) {
      // Error management
    }
    
    return result;
  }
```

**Comment by TrejGun** [comment]
that would be good to add example of how to validate signature in javascript

**Comment by wenge8n** [comment]
Hi @TrejGun 
were you able to write solution using javascript?
If then, hope to hear response from you.
Thanks

**Comment by TrejGun** [comment]
@wenge8n 
i guess you are looking for this
https://trejgun.github.io/articles/biometric-authentication-for-nestjs

**Comment by wenge8n** [comment]
Hi @TrejGun 
thank you for your instruction. I believe you are correct.
Also my purpose was a little different. I had to store the public key on local and verify the signature locally. If anybody have the same purpose, this will help you with this library.
https://www.npmjs.com/package/react-native-rsa-native

**Comment by joviksdev** [comment]
> @wenge8n i guess you are looking for this https://trejgun.github.io/articles/biometric-authentication-for-nestjs

This can't be found

**Comment by TrejGun** [comment]
@joviksdev you can find code here
https://github.com/GemunIon/nestjs-auth/tree/master/apps/biometric
