### ISSUE TITLE
npm package version

### ISSUE THREAD

**Issue by liunian-zy** [SelfLender/react-native-biometrics#218]
Hi! The latest version on npmjs is 3.0.1, but 2.2.2 is installed by default. This does not match the master branch, so following the documentation will give an error, e.g.
`undefined is not a function` (BiometryTypes)
`TypeError: constructor is not callable ` (new ReactNativeBiometrics())
If someone encounters such an error, just install version 3.0.1, otherwise you should follow the readme in the package you installed instead of the one on github. By the way, the 3.0.0 version will also have the above problems.
I don't know if npmjs can adjust the version installed by default, or if it can be noted in the documentation. It took me a day to solve this situation (hahaha, I am using this component for the first time).

(Sorry my English is not very good, the above is from Google Translate)

**Comment by jayfunk** [comment]
Fixed. Thanks for letting me know!
