### ISSUE TITLE
Example using .NET

### ISSUE THREAD

**Issue by chaukhanh211** [SelfLender/react-native-biometrics#221]
Has anyone implemented this on a .NET ?

can someone provide an example using C# ?

**Comment by SabbeAndres** [comment]
Yes i have made a full working version in production. I will try and make an example solution using dotnet 6 and minimal api's  and make a pull request for it.

**Comment by chaukhanh211** [comment]
### My code:
```
public static bool VerifySignature(string publicKey, string signature, string msg)
        {
            try
            {
                var publicKeyBytes = PublicKeyFactory.CreateKey(Convert.FromBase64String(publicKey));
                byte[] msgBytes = Encoding.UTF8.GetBytes(msg);
                byte[] sigBytes = Convert.FromBase64String(signature);

                ISigner signer = SignerUtilities.GetSigner("SHA256withRSA");
                signer.Init(false, publicKeyBytes);
                signer.BlockUpdate(msgBytes, 0, msgBytes.Length);
                return signer.VerifySignature(sigBytes);
            }
            catch (Exception exc)
            {
                Console.WriteLine("Verification failed with the error: " + exc.ToString());
                return false;
            }
        }
```

**Comment by SabbeAndres** [comment]
Yup, i almost have the same function, with the only difference that my production code was written in VB.NET (i didn't have a choice sadly).
But a generic server-client example in this repo would be very helpful.

**Comment by jayfunk** [comment]
Would love a PR with an example of server side implementation. Closing as it seems this issue has been resolved.

**Comment by JamesIde** [comment]
@SabbeAndres any update on this?

**Comment by JamesIde** [comment]
@SabbeAndres @chaukhanh211 Came up with something like this :
```
public static bool VerifySignature(string publicKey, string signature, string payload)
        {
            byte[] publicKeyBytes = Convert.FromBase64String(publicKey);
            byte[] signatureBytes = Convert.FromBase64String(signature);
            byte[] dataBytes = Encoding.UTF8.GetBytes(payload);

            var rsa = RSA.Create();
            rsa.ImportSubjectPublicKeyInfo(publicKeyBytes, out _);

            try
            {
                return rsa.VerifyData(dataBytes, signatureBytes, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
            }
            catch (Exception ex)
            {
                // Handle ArgumentNullException | ArgumentException | CryptographicException
                throw ex;
            }

        }
```
Noting that rsa.VerifyData does the following:

_"Verifies that a digital signature is valid by calculating the hash value of the specified data using the specified hash algorithm and padding, and comparing it to the provided signature."_

**Comment by AbuMandour** [comment]
> @SabbeAndres @chaukhanh211 Came up with something like this :
> 
> ```
> public static bool VerifySignature(string publicKey, string signature, string payload)
>         {
>             byte[] publicKeyBytes = Convert.FromBase64String(publicKey);
>             byte[] signatureBytes = Convert.FromBase64String(signature);
>             byte[] dataBytes = Encoding.UTF8.GetBytes(payload);
> 
>             var rsa = RSA.Create();
>             rsa.ImportSubjectPublicKeyInfo(publicKeyBytes, out _);
> 
>             try
>             {
>                 return rsa.VerifyData(dataBytes, signatureBytes, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
>             }
>             catch (Exception ex)
>             {
>                 // Handle ArgumentNullException | ArgumentException | CryptographicException
>                 throw ex;
>             }
> 
>         }
> ```
> 
> Noting that rsa.VerifyData does the following:
> 
> _"Verifies that a digital signature is valid by calculating the hash value of the specified data using the specified hash algorithm and padding, and comparing it to the provided signature."_

then how backend verify that the payload is the same as the mobile sent, for example, if I sent from the mobile payload like "any message", how API will know that is the payload?

**Comment by JamesIde** [comment]
@AbuMandour my apologies but this was for a hobby project that I ended up abandoning. I was looking through the code and left some comments about how I was unsure of the exact thing that you mentioned. Sorry I can't be of any help beyond the VerifySignature method. :(
