### ISSUE TITLE
What kind of authentication is enrolled on the device

### ISSUE THREAD

**Issue by Vitalik7** [SelfLender/react-native-biometrics#222]
How I can to know what kind of authentication is enrolled on the device ?

**Comment by jayfunk** [comment]
I believe that `isSensorAvailable` will do what you expect. The I dont think the sensor will be reported if it is not registered/enrolled by the user.

**Comment by tamlyn** [comment]
My experience is that on (at least some) Android devices, `isSensorAvailable` returns true whether or not there are any identities (e.g. fingerprints) enrolled, provided the device has biometrics capabilities *and* the device has a screen lock (e.g. PIN or pattern). Subsequently calls to `createKeys` fail with `Error generating public private keys`.

**Comment by ivanseedz** [comment]
> My experience is that on (at least some) Android devices, `isSensorAvailable` returns true whether or not there are any identities (e.g. fingerprints) enrolled, provided the device has biometrics capabilities _and_ the device has a screen lock (e.g. PIN or pattern). Subsequently calls to `createKeys` fail with `Error generating public private keys`.

Hi, how did you get around this situation @tamlyn?

**Comment by tamlyn** [comment]
I don't think I found a solution. It wasn't critical for our app.

**Comment by ivanseedz** [comment]
Hi, i'm find this discussion in [stackoverflow](https://stackoverflow.com/questions/56869602/java-lang-illegalargumentexception-device-credential-not-supported-with-crypto). I believe the problem is related to him. But if disable `allowDeviceCredentials`, i don't see this error again.
