### ISSUE TITLE
How to Detect Biometric Change

### ISSUE THREAD

**Issue by selfishprogrammer** [SelfLender/react-native-biometrics#223]
How can i know if my biometric got changed , i want to show a prompt when my biometric got changed .  Can anyone help me on this issue thanks.

**Comment by jayfunk** [comment]
I am not totally sure, but checking `biometricKeysExist` might reflect if the key has been changed since the KeyStore holds the current value. I am not sure if the OS's will invalidate or remove the key from this store if the biometric information was changed. May have to test this out some.

**Comment by paperskyline** [comment]
I am stuck on this too. On android `biometricKeysExist` becomes false if a new fingerprint is added, but no change if the fingerprint is removed. On ios the `biometricKeysExist` does not become false even if reset or add new FaceId.

Has anyone found a solution to this?

**Comment by xuanmai-agilityio** [comment]
Please refer to this [#245](https://github.com/SelfLender/react-native-biometrics/issues/245)
