### ISSUE TITLE
Biometry is not enrolled

### ISSUE THREAD

**Issue by stefanparezanovic-cb** [SelfLender/react-native-biometrics#227]
"react": "18.1.0",
"react-native": "0.70.0",
"react-native-biometrics": "^3.0.1"

```
import ReactNativeBiometrics from 'react-native-biometrics';

const BiometricsView = () => {
    ReactNativeBiometrics.isSensorAvailable().then((resultObject) => {
      const { available, biometryType } = resultObject;

      if (available && biometryType === ReactNativeBiometrics.TouchID) {
        console.log("TouchID is supported");
      } else if (available && biometryType === ReactNativeBiometrics.FaceID) {
        console.log("FaceID is supported");
      } else if (
        available &&
        biometryType === ReactNativeBiometrics.Biometrics
      ) {
        console.log("Biometrics is supported");
      } else {
        console.log("Biometrics not supported");
      }
    });
};

export default BiometricsView;

```
also i have added this line into info.plist
```
	<key>NSFaceIDUsageDescription</key>
	<string>$(PRODUCT_NAME) Authentication with TouchId or FaceID</string>
```
when i log resultObject i get
```
resultObject :>>  
{
  "available": false,
  "error": "Error Domain=com.apple.LocalAuthentication Code=-7 \"No identities are enrolled.\" UserInfo= 
  {NSDebugDescription=No identities are enrolled., NSLocalizedDescription=Biometry is not enrolled.}"
}
```

**Comment by jayfunk** [comment]
This usually means the device you are using does not have any biometric information registered. What kind of device are you testing this on?On Nov 7, 2022, at 16:52, stefanparezanovic-cb ***@***.***> wrote:﻿
"react": "18.1.0",
"react-native": "0.70.0",
"react-native-biometrics": "^3.0.1"
import ReactNativeBiometrics from 'react-native-biometrics';

const BiometricsView = () => {
  ReactNativeBiometrics.isSensorAvailable().then(resultObject => {
    const { available, biometryType } = resultObject;
    if (available && biometryType === ReactNativeBiometrics.TouchID) {
      console.log('TouchID is supported');
    } else if (available && biometryType === ReactNativeBiometrics.FaceID) {
      console.log('FaceID is supported');
    } else if (available && biometryType === ReactNativeBiometrics.Biometrics) {
      console.log('Biometrics is supported');
    } else {
      console.log('Biometrics not supported');
    }
  });
};

export default BiometricsView;


also i have added this line into info.plist
	<key>NSFaceIDUsageDescription</key>
	<string>$(PRODUCT_NAME) Authentication with TouchId or FaceID</string>

when i log resultObject i get
resultObject :>>  
{
  "available": false,
  "error": "Error Domain=com.apple.LocalAuthentication Code=-7 \"No identities are enrolled.\" UserInfo= 
  {NSDebugDescription=No identities are enrolled., NSLocalizedDescription=Biometry is not enrolled.}"
}

**Comment by stefanparezanovic-cb** [comment]
Im using on IOS simulator.

**Comment by zarozhenya** [comment]
> Im using on IOS simulator.

It is possible to use a Face ID on simulator. All you have to do is go to **Features -> Face ID -> Enrolled** and click on this button.

**Comment by jayfunk** [comment]
Closing as it seems like this might be related to the simulator not having biometric authentication enabled.
