### ISSUE TITLE
App crashes on certain devices

### ISSUE THREAD

**Issue by andreifilip123** [SelfLender/react-native-biometrics#24]
Hello,

This package causes the app to crash on certain devices. I'll put the list below. Thanks 😄 

Samsung Galaxy J4+ (SM-J415FN)
Samsung Galaxy J3 2017 (SM-J330FN)
Samsung A3 2015 (SM-A300FU)

**Comment by NappyPirate** [comment]
Unfortunately, I have not been able to test with these devices.  Can you please provide the versions of react, react-native, and react-native-biometrics that you are using as well as the OS versions?  Also, can you provide the stack trace or error message that you are receiving?

**Comment by andreifilip123** [comment]
I don't have the exact stack trace.. I fixed the problem by putting the Biometrics detection inside a try catch and if it fails, I set the biometric type to 'none'.

**Comment by andreifilip123** [comment]
I'm not sure if it's related to #22 . It fails in the same place but I think it's not related since I can guarantee that all those devices are not rooted. Also, I heard that rooted devices can't use fingerprint since they have some kind of flag.

**Comment by NappyPirate** [comment]
Closing this issue since the Android implementation has been refactored to use the new BiometricPrompt API and should hopefully resolve these errors.  We can re-open this issue if the problems persist.
