### ISSUE TITLE
Call back issue in createSignature.

### ISSUE THREAD

**Issue by jile10** [SelfLender/react-native-biometrics#25]
after the verification of my fingerprint then cancel the dialog. It gives an error 

> The callback createSignature() exists in module ReactNativeBiometrics, but only one callback may be registered to a function in native module

**Comment by NappyPirate** [comment]
Closing this issue since the Android implementation has been refactored to use the new BiometricPrompt API in version 2.0.0 and should hopefully resolve errors like these.  We can re-open this issue if the problems persist.
