### ISSUE TITLE
FaceId not recognized in android

### ISSUE THREAD

**Issue by mamtacipl** [SelfLender/react-native-biometrics#28]

**Comment by mamtacipl** [comment]
Biometrics.isSensorAvailable() never return FaceId. FaceId is added on device setting but it return null.

**Comment by NappyPirate** [comment]
Currently this library uses the now deprecated [FingerprintManager](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager) for biometrics in Android.  Unfortunately, that only provides fingerprint capabilities on Android.  I believe that this issue and issues with other forms of biometrics on Android will be resolved by implementing the new android biometrics API #15
