### ISSUE TITLE
Could not find aapt2-proto.jar 

### ISSUE THREAD

**Issue by gedu** [SelfLender/react-native-biometrics#30]
Hey I wanna record this issue, I already created a PR for this

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-biometrics'.
> Could not resolve all artifacts for configuration ':react-native-biometrics:classpath'.
   > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar

Only have to change the order of google() and jcenter() to make this work. I will be using my fork until you merge this

https://github.com/SelfLender/react-native-biometrics/pull/29

Thanks

**Comment by NappyPirate** [comment]
Thank you for the pull request.  This has been merged and released in version [1.5.2](https://github.com/SelfLender/react-native-biometrics/releases/tag/1.5.2)
