### ISSUE TITLE
Error on android

### ISSUE THREAD

**Issue by TheGuy68** [SelfLender/react-native-biometrics#33]
Ok so to test this I made a brand new application and tried this lib and it works great.
Then I installed this into our app and then get this error.

Possible Unhandled Promise Rejection (id: 0):
06-15 17:55:38.323 13994 14660 W ReactNativeJS: Error: Error generating signature
06-15 17:55:38.323 13994 14660 W ReactNativeJS: createErrorFromErrorData@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2106:26
06-15 17:55:38.323 13994 14660 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2058:51
06-15 17:55:38.323 13994 14660 W ReactNativeJS: __invokeCallback@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2625:23
06-15 17:55:38.323 13994 14660 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2356:34
06-15 17:55:38.323 13994 14660 W ReactNativeJS: __guard@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2529:15
06-15 17:55:38.323 13994 14660 W ReactNativeJS: invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2355:21
06-15 17:55:38.323 13994 14660 W ReactNativeJS: invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by hansyulian** [comment]
hey, i get this issue also, so what actually happened and how to fix it?

**Comment by MayoudP** [comment]
Got the same, I suppose this one happen when the private key on the phone has been deleted.
So probably you need to call again `createKeys()`, but it mean's that you should send again the public key to the server...
