### ISSUE TITLE
Properly Identify Failed Fingerprint vs Cancel

### ISSUE THREAD

**Issue by JeffreyLeeDave** [SelfLender/react-native-biometrics#34]
So I am using the library and when I click cancel on the fingerprint prompt or failed the fingerprint prompt, it gives the same error making them indistinguishable:

`Could not confirm fingerprint`

Maybe I am not looking hard enough, but is there a way for me to distinguish these errors. I want to show something on fingerprint failure, but nothing on cancel.

**Comment by kimihiro64** [comment]
This can probably be tied together with #40. I would suggest when the promise rejects, the catch gets enumeration (Biometrics.UserCancelled, Biometrics.Invalid, Biometrics.Failed, BioMetrics.NotConfigured, etc).
