### ISSUE TITLE
How can I run in expo?

### ISSUE THREAD

**Issue by dalv-happy** [SelfLender/react-native-biometrics#35]
Hello!
I have expo project. 
I installed package, then I linked package into a project
via
`react-native link react-native-biometrics`

But I got the error message
https://monosnap.com/file/BuKsNgXEo4vjnkMgvMWCNloAdnPMay

**Comment by NappyPirate** [comment]
This library requires native code in order to access the key stores in android and iOS.  Unfortunately, it appears that expo does not easily allow for native code implementations: https://docs.expo.io/versions/latest/introduction/faq/#how-do-i-add-custom-native-code
