### ISSUE TITLE
Decoding on Server signature based on public key generated in JAVA

### ISSUE THREAD

**Issue by virtualrizwan** [SelfLender/react-native-biometrics#38]
Hi, 
I am able to successfully create PublicKey and Signature that I send back to server. 
Server Code is written in LifeRay (Java). I am not able to decode the signature with Generated publicKey. 
Any help in this will be highly appreciated.

**Comment by NappyPirate** [comment]
Please see issue #21 
I'm closing this issue as a duplicate
