### ISSUE TITLE
Not able to verify signature using public key in java

### ISSUE THREAD

**Issue by pradeepnarayan007** [SelfLender/react-native-biometrics#39]
I am trying to verify biomatric signature using the code in java with public key not not able to verify .
Please help me to know which algorithm i should use.
Below are sample 
### PUBLIC KEY  001 ###
 
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwRAOJkDdfryjDUIl11coCPok25bCW8K7GhrxHA9tC7GUmuWPZtAGN+Nf25E8SV8BZRRx7T0p26IShzwcP5mHYJczERy7s3DDqrsAnmf2YFAv7VYYibSGhmvVBPJCWbt5SsiP5WhskUOvc/96LRKt6N2ubaH/0UN59VtWIIy0FoZdi6lhyqbFFTV/IfTT1m7UspRz8MtXtS5bahurwLtYGw173rxQ2MXZWyGgVUv75lQ3KdPV59eTMXwwmzVTBvkA5pyq/yn+Kc3xzzEj8uafaUpl9y9yjfdAY+T+dRKsrEhEkmITcl1kj9G5nID1rSJCG9VVP+6dtwK6KqKeIYf9lwIDAQAB
 
 
 
### CERTIFICATE 001 ###
 
lO1qCyAL9cGgor3tgclwLQm8o7OBnvTM9rR3HlLyhCyclprDp1Z01nA7LmN1prClE5PjBGNSUKREssRv42lGmutTNkgDrzRG+sMPraVjw5eJUqEHTpp9E122pHpp1W1pCV6kQBtFXigZe9h5Vms/fUmieK9jkmzmJfJOv28KnDMmAGIFEyTmkZ0/PeVfOldmF6xsjsownZKiIVnw6ZZgEIUG6yTe2gA6Xh174uNP9HuDI2KgivhXWOoxyiE0U+Ri9lccXn40iKoVe5m+SD0TRFepSHf//GdXi0t7WtYMbTTG48ots7gfcctafoRE4PBn6jbg/R5RIkCrj7m+U9X3jw==
 
JIExsj8aLTRUM0OVfoBPaKR2h4oqtEDUo5NPy6EsAAYnsVvGHERCikl1ctTv2k3RHcgZUqmdcCfT2Uekxi3efblFLdB5Mvjl8Ju+RXRNZT5813GLahhtDjgiAM3W4pTxIAsRFbsNPY0O4NfKQXqDYcReI+7P+nR/QzmM5SIB2cc+k+nrcPpGA6gihyrY++se7itPz/ImG8fL6QdZdyD5i5gZAWVXhZTeEdLOOKGDIzPsxUBTIwJm4B+saBwj+sfa48w47ueLPDnU6ayGqsFE3mOZmV6L+EoTJT7R9WIKNFa3QGfxD/bew6zfWoms4qx/hI+TdxxgTfTOc/lRtVlrgg==
 
LJMTn1IwmyxyFfeNxOCcWrsCFwdJY8ANQ5iyzfgPn2Y1rs/e5xzO011867k5uBV25MvY+6WhF51QjdIxuRw8DzalXrsGRtN62rfYrQDqX/VErjaQEDG5YkV3tc/zhGbjhLJtUpvbwnXyHA+LI96MNQTEPXDwwNmEKMN7Ia8xIi/5fuNYbc0aLM6r9c63tD8u5l3K8tAkVByWHKcRfrYXL4sxL7hGQSOFtnCEDRPud9J9SNHpD4OcqpvzVKwFOHMHssKo3MCsAhVkTFkIohQoj5d812h1HWixxshilErIIQvuWhjBhkbbSrREk1FTYtlkh+nh0f8CqGSpy+sbxVYfUw==

**Comment by pradeepnarayan007** [comment]
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;

import org.apache.commons.codec.binary.Base64;

public class VerifyDigitalSignature {
    public static void main(String[] args) {
        try {
           // byte[] publicKeyEncoded = Files.readAllBytes("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtAd4Yub4zp2JYl8tT8n5JIxhjn5R++0viIhXlvrevRsYCLSD6ENZSKpiZhrgjxd/ZkwhHlQgVypkRr1nA70JA402OIiKJj43LS1n8//t5y3DpTJlu1gaTJe1ylJFzRuPB9be2UHvNCm2KFZ8dvJq/cKINrMCsyBHsRwOHrly2uauf3mMpdABore3cxRLkhbNoSARBsUja+qohUHu4Xx+BlTTi2IzMhB0Fx3GKyiFHsvlWuJsa6MGHEZW9MI3Xq9YIzP5+NZc8H28/bCDC0FCoDL4/xbjZ2CLW/j85s3Pf/K+3kvIXaP5a59cFrDbbUOEEZM3aKxgVa9tuOVNw33EbQIDAQAB");
          //  byte[] digitalSignature = Files.readAllBytes(Paths.get("signature"));

            
            byte[] publicKeyEncoded = Base64.decodeBase64("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtAd4Yub4zp2JYl8tT8n5JIxhjn5R++0viIhXlvrevRsYCLSD6ENZSKpiZhrgjxd/ZkwhHlQgVypkRr1nA70JA402OIiKJj43LS1n8//t5y3DpTJlu1gaTJe1ylJFzRuPB9be2UHvNCm2KFZ8dvJq/cKINrMCsyBHsRwOHrly2uauf3mMpdABore3cxRLkhbNoSARBsUja+qohUHu4Xx+BlTTi2IzMhB0Fx3GKyiFHsvlWuJsa6MGHEZW9MI3Xq9YIzP5+NZc8H28/bCDC0FCoDL4/xbjZ2CLW/j85s3Pf/K+3kvIXaP5a59cFrDbbUOEEZM3aKxgVa9tuOVNw33EbQIDAQAB");
            byte[] digitalSignature = Base64.decodeBase64("TamlfnFp6Gfvd1eyHPiyZZl7gDYioFWc8Zo5iASdIkaRB01sF2LyjHC/BitnF2pJh+bPtSh/yLfsvxZC5QlQRMQ58ci2SzsAIztD7FKuZRNezFZMRU/Rk3pMTk/cm79iSXw4G4uz8jDUcUW2D+NjELdJTTNAvSopgpA1eePOQ7tGVPsafFs3aF/qT/msj75DeO+60q/quxJvEXSMREJnTBavt2d0YGOXZOCt1e13BX0akqQq7e9gh0eJisrdoXreAUdNtl9Ea3IuK3XAwZpk2lp8p2TNBRrEtaHt9OvhmEzPzr0x5wDwfgXqTN3IHLblfwzTGk2V8Fe3HEdq2Ndl4w==");
            
            X509EncodedKeySpec publicKeySpec = new X509EncodedKeySpec(publicKeyEncoded);
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");

            PublicKey publicKey = keyFactory.generatePublic(publicKeySpec);	
            Signature signature = Signature.getInstance("SHA256withRSA");
            signature.initVerify(publicKey);

           // byte[] bytes = Files.readAllBytes(Paths.get("README"));
            //signature.update(bytes);

            boolean verified = signature.verify(digitalSignature);
            if (verified) {
                System.out.println("Data verified.");
            } else {
                System.out.println("Cannot verify data.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by NappyPirate** [comment]
Please see issue #21 
I'm closing this issue as a duplicate
