### ISSUE TITLE
Not Detecting face Recognition sensor

### ISSUE THREAD

**Issue by Mubashirmarwat** [SelfLender/react-native-biometrics#49]
I am trying to check if face recognition and fingerprint is available in a phone or not by the below code:

```
 Biometrics.isSensorAvailable()
        .then((biometryType) => {

                
                if (biometryType === Biometrics.TouchID) {
                    console.log('fingerprint')
                    this.setState({ finger: true })
                }

                if (biometryType === Biometrics.FaceID) {
                    console.log('face Recognition')
                  this.setState({ false: true })
              } 
            })
```

Its working fine in case of finger print but unable to detect face recognition sensor.
I have tested it in android (Samsung S10 Plus).

 "react": "16.9.0",
 "react-native": "0.61.2",
"react-native-biometrics": "^1.6.1"

**Comment by NappyPirate** [comment]
https://github.com/SelfLender/react-native-biometrics/issues/15
