### ISSUE TITLE
createSignature doesn't open prompt on iOS 13.1

### ISSUE THREAD

**Issue by mohit8189** [SelfLender/react-native-biometrics#50]
I am calling "Biometrics.createSignature('Please authenticate to proceed.', payload)" in componentDidMount function but it doesn't open alert for biometric authentication but when I touch fingerprint button then it appears for authentication. 
I have faced this issue in library version 1.6.0 and updated to 1.7.0 but still facing same.

**Comment by NappyPirate** [comment]
Closing in favor of #46

**Comment by mohit8189** [comment]
It is resolved in iOS 13.2
