### ISSUE TITLE
isBiometricKeyExists

### ISSUE THREAD

**Issue by TrejGun** [SelfLender/react-native-biometrics#52]
please add some method to check if key was generated and stored before calling createSignature

**Comment by MayoudP** [comment]
@NappyPirate About this, can you tell me what could be the reasons for a failed `createSignature()` ? I've got some users where this method crashed, and throw me an error... 
Is this because keys were removed (`Biometrics.deleteKeys()`) and that's why attempting signature failed ? Or could it be because of another reason(s) ?

**Comment by TrejGun** [comment]
@MayoudP in my case error is 

![Simulator Screen Shot - iPhone 11 - 2019-11-13 at 14 59 37](https://user-images.githubusercontent.com/185285/68765787-45ee7200-0626-11ea-9b1c-202aad61ea26.png)

but this is only part of the problem

in our app we want to show button on login screen only when biometric auth was set up in profile previously, and there is no way to check this using this lib so we are using workarounds

**Comment by MayoudP** [comment]
Is this the error you get when you call `createSignature()` and when user didn't do `createKeys()` previously ?

**Comment by TrejGun** [comment]
yes

**Comment by MayoudP** [comment]
> yes
> 
> this is emulator, newer tried on real device

Maybe you can add do something like that to handle the case if createSignature() "failed".

**Comment by TrejGun** [comment]
thats what i'm doing now) thanks

**Comment by srslafazan** [comment]
I would like to see the proposed feature too :+1:

**Comment by NappyPirate** [comment]
a `biometricKeyExists` function was added in version 2.0.0

**Comment by TrejGun** [comment]
thanks

**Comment by MayoudP** [comment]
I have a question @NappyPirate when you update your application through the store, is it deleting the key previously created with previous version ? Or does updating your application doesn't have any effect on the keychain and the key created before with older version of your app ?
