### ISSUE TITLE
Error displaying local biometric prompt on Sumsung

### ISSUE THREAD

**Issue by Bardiamist** [SelfLender/react-native-biometrics#58]
Couple Samsung users have
```
Error displaying local biometric prompt: must have com.samsung.android.bio.face.permission.USE_FACE or android.permission.USE_BIOMETRIC permission.
```
That happens when in `Preferred biometric` is selected `Face recignition`.

Any ideas how to fix it?

**Comment by Bardiamist** [comment]
Seems [answer here](https://stackoverflow.com/a/58311889/5507373)

**Comment by Bardiamist** [comment]
Also Samsung (Galaxy S8) users have
```
Unable to pause activity {com.valr.app/com.valr.app.MainActivity}: java.lang.SecurityException: Must have com.samsung.android.bio.face.permission.USE_FACE or android.permission.USE_BIOMETRIC permission.
```
on home button press when `Face recignition` preferred.

**Comment by acoutts** [comment]
Make sure you're requesting those permissions it's saying it doesn't have.

https://facebook.github.io/react-native/docs/permissionsandroid
