### ISSUE TITLE
Cant install via pod

### ISSUE THREAD

**Issue by sintylapse** [SelfLender/react-native-biometrics#66]
Getting this error after running `pod install`
```
[!] CocoaPods could not find compatible versions for pod "react-native-biometrics":
  In Podfile:
    react-native-biometrics (from `../node_modules/react-native-biometrics`)

Specs satisfying the `react-native-biometrics (from `../node_modules/react-native-biometrics`)` dependency were found, but they required a higher minimum deployment target.
```
Tried reinstall node_modules, project pods, cocoapods tool itself, nothing helps

**Comment by sintylapse** [comment]
Doing some incomprehensible for human brain mysterious magic helped

**Comment by lukerollans** [comment]
You likely changed your iOS deployment target from < 10.0 to >= 10.0

**Comment by sintylapse** [comment]
> You likely changed your iOS deployment target from < 10.0 to >= 10.0

No, it didn’t help. It seems the problem was in lock file

If I increment deployment target to 10, does this mean that users with IOS 9 won’t be able to download the app?

**Comment by antojiku** [comment]
I have the same issue and change the deployment target to 10 doesn't work
Is there any solution?

**Comment by antojiku** [comment]
> Doing some incomprehensible for human brain mysterious magic helped

how did you solve it?

**Comment by sintylapse** [comment]
> how did you solve it?
Not really sure, I did different things. Try delete pods lock file and run pod install again. Tell me if that won’t work

**Comment by antojiku** [comment]
> > how did you solve it?
> 
> Not really sure, I did different things. Try delete pods lock file and run pod install again. Tell me if that won’t work

Oh my bad, I forgot change _platform :ios_ to 10 in my Podfile.

**Comment by sintylapse** [comment]
> Oh my bad, I forgot change _platform :ios_ to 10 in my Podfile.

Hmm, weird, platform :ios, '9.0' works fine for me

**Comment by cmejet** [comment]
I installed react-native-biometrics, increased my iOS target version to 10, but this does NOT update the Pod File target so I got an error as described above.  Simply changing the value in the pod file resolved this for me.
