### ISSUE TITLE
return "Biometrics not supported" after multiple time wrong touchid.

### ISSUE THREAD

**Issue by govind1530** [SelfLender/react-native-biometrics#75]
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 181.36 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

//code

                 ReactNativeBiometrics.isSensorAvailable()
                      .then((resultobject)=>{
                           const {available,biometryType}=resultobject
                             if (available && biometryType === ReactNativeBiometrics.TouchID) {
                               console.log('TouchID is supported')
                             ReactNativeBiometrics.simplePrompt({promptMessage: 'Confirm fingerprint'})
                     .then((resultObject) => {
                       const { success } = resultObject
       
                   if (success) {
                      console.log('successful biometrics provided')
                 } else {
                   RNExitApp.exitApp();
               }
            })
                .catch(() => {
              RNExitApp.exitApp();
            })
             } else if (available && biometryType === ReactNativeBiometrics.FaceID) {
             console.log('FaceID is supported')
   
          } else if (available && biometryType === ReactNativeBiometrics.Biometrics) {
              console.log('Biometrics is supported')
     
             } else {
            console.log('Biometrics not supported')
          }
        })

i am using iphone 6s  in first its show poup but after multiple wrong input its give error "biometric not supported" after uninstall and install its give same error.its work when lock the device and unlock it its work perfectly but after multiple wrong input same issue again

**Comment by NappyPirate** [comment]
Biometrics becomes "locked" on iOS after multiple failed attempts, and will remain locked until the user enters their passcode.
https://stackoverflow.com/questions/41934228/how-much-time-is-locked-touch-id-biometry-is-locked-out

**Comment by govind1530** [comment]
Thanks @NappyPirate
