### ISSUE TITLE
Android FaceID

### ISSUE THREAD

**Issue by IronTony** [SelfLender/react-native-biometrics#77]
Hi, thank you for the package, using a lot.
Just a quick question, what about the FaceID in Android? Is it possible or not? I saw that they introduced something for Android 10.

Do you plan an update of the package.

**Comment by TNicholson11** [comment]
It's already supported.. I just migrated our application from react-native-touch-id to react-native-biometrics specifically for Android "Face ID". Android's biometric library doesn't return a "fingerprint" or "face" sensor.. just that one exists. The user is then prompted and, depending on their device, can select between fingerprint or face to do a biometric unlock.

**Comment by IronTony** [comment]
Oh nice. Thank you so much for the answer.
All the best

**Comment by JZorina** [comment]
@TNicholson11 - can you help me with that please? i am using Android 10 - with only face configure on my device - and getting this error "Error generating public private keys " - everytime the method createKeys() is running. 
what can i do to fix it?

**Comment by DanyalAslam** [comment]
Hi is there any method for android to specify which authentication method to choose between face if and biometric
if user wants to authenticate using face id we allow him using fcae id, if user wants to go with thumb input we allow him using thumb impression
