### ISSUE TITLE
Not even a single example?!

### ISSUE THREAD

**Issue by bimix** [SelfLender/react-native-biometrics#79]
Really guys? You couldn't even upload a single example project?

**Comment by JonathanSohNUS** [comment]
Assuming your device has some form of biometric support, if you run the example code given sequentially it forms a "working example"

If your priority is to just get the fingerprint prompt out, the example codes from README.md provided in the createSignature or simplePrompt would suffice.

**Comment by bimix** [comment]
Nah I just found out that this doesnt support fingerprint for Android.

**Comment by jayfunk** [comment]
This library does support fingerprint for Android.
